settings:
  name: CI Tests for my Hello C World

tests:
  assertReturnCode: 0
  install:
  - [ apt install -qq -y gcc make ]
  build:
  - [ make ]
  run:
    assertStdoutContains: "Hello World"
    your_project:
    - [ ./hello ]
