settings:
  name: CI Tests for my Hello C World

import:
- "satori://code/trufflehog.yml"

tests:
  assertReturnCode: 0
  build:
  - [ make ]

  run:
    assertStdoutContains: "An expected output" # assert the output of    the main system execution of your project
    your_project:
    - [ ./my_project ]
