settings:
  name: CI Tests for my Hello C World

tests:
  # all executions will return 0
  assertReturnCode: 0
  update:
    - apt update
  install:
    - apt install -qy gcc make
  build:
    - make
  run:
    # and the output will be validated
    assertStdoutContains: "Hello World"
    your_project:
      - ./hello
